### ISSUE TITLE
RawGit shutting down

### ISSUE THREAD

**Issue by Lukas34** [richorama/AzureSpeedTest2#29]
I just noticed that [RawGit](https://rawgit.com/), the CDN used to deliver the country flags, is shutting down - since late 2018. The service promised to serve files until at least October of 2019 and could theoretically shut down any day now.
Maybe the service should be replaced just to be sure that the site continues to work when RawGit eventually shuts down.

**Comment by richorama** [comment]
thanks for the heads up @Lukas34, I'll seek an alternative solution.
