### ISSUE TITLE
Azure Speed Test Page does not occure at a correct shape

### ISSUE THREAD

**Issue by Fajky** [richorama/AzureSpeedTest2#33]
When i go to https://azurespeedtest.azurewebsites.net/ via any browser, I see ony picture from attachment. Shoul I change something at browser setting?
![AzureSpeedTest](https://user-images.githubusercontent.com/66954916/84660971-ee94e500-af19-11ea-8b9b-7a5435fd0aec.JPG)

**Comment by richorama** [comment]
Could this be an Internet Explorer issue? Have you tried any other browsers?

**Comment by Fajky** [comment]
Hello, yes, I have tried IE, Chrome and Firefox and the result was the same.  Also trying on 3 different serves

**Comment by richorama** [comment]
I suspect JavaScript is not enabled, I have added a `<noscript />` tag to the page to detect this.
