### ISSUE TITLE
Norway East as best option in Buenos Aires is probably wrong

### ISSUE THREAD

**Issue by mensaboy** [richorama/AzureSpeedTest2#41]
![Screen Shot 2021-10-15 at 09 48 03](https://user-images.githubusercontent.com/17498796/137490316-f045bbbd-ee09-45ea-be1b-09c1b353d477.png)

https://azure.microsoft.com/en-us/updates/brazil-south-availability-zones-now-generally-available/

**Comment by richorama** [comment]
fixed (temporarily)
